version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    container_name: dev_database_cont
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5442:5432
    environment:
      - POSTGRES_DB=rose_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  cache:
    image: redis:6.2-alpine
    container_name: dev_redis_cont
    ports:
      - '6389:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

volumes:
  postgres_data:
  cache:
