version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    container_name: dev_database_cont
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5442:5432
    environment:
      - POSTGRES_DB=rose_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data:
  cache:
