version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=rose
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - /etc/oroose_test:/config
    ports:
      - "8000:8000"
    environment:
      - LOAD_CONFIG_PATH=/config/.env.test
      - MAIN_PROCESS=TESTING
    depends_on:
      - db

  cache:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

  celery:
    build: .
    command: celery -A oroose worker -l info
    volumes:
      - .:/code
      - /etc/oroose_test:/config
    environment:
      - LOAD_CONFIG_PATH=/config/.env.test
      - MAIN_PROCESS=TESTING
    depends_on:
      - db
      - cache

  celery-beat:
    build: .
    command: celery -A oroose beat -l info
    volumes:
      - .:/code
      - /etc/oroose_test:/config
    environment:
      - LOAD_CONFIG_PATH=/config/.env.test
      - MAIN_PROCESS=TESTING
    depends_on:
      - db
      - cache

volumes:
  postgres_data:
  cache: