version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=rose
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - /home/ramesh/Desktop/test:/config
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=rose
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - LOAD_CONFIG_PATH=/config/config.json
    depends_on:
      - db

  cache:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
volumes:
  postgres_data:
  cache: