version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    container_name: test_database_cont
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=rose_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    container_name: test_web_cont
    command: >
      bash -c "python manage.py migrate
      && python manage.py load_param_settings
      && python manage.py runserver 0.0.0.0:8005"
    volumes:
      - .:/code
      - /etc/oroose_test:/config
      - /var/log/oroose_test:/log
    ports:
      - "8005:8005"
    environment:
      - LOAD_CONFIG_PATH=/config/.env.test
      - MAIN_PROCESS=TESTING
      - POSTGRES_DB=rose_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  cache:
    image: redis:6.2-alpine
    container_name: test_redis_cont
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

  celery:
    build: .
    container_name: test_celery_worker_cont
    command: celery -A oroose worker -l info
    volumes:
      - .:/code
      - /etc/oroose_test:/config
      - /var/log/oroose_test:/log
    environment:
      - LOAD_CONFIG_PATH=/config/.env.test
      - MAIN_PROCESS=TESTING
      - POSTGRES_DB=rose_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - cache

  celery-beat:
    build: .
    container_name: test_celery_beat_cont
    command: celery -A oroose beat -l info
    volumes:
      - .:/code
      - /etc/oroose_test:/config
      - /var/log/oroose_test:/log
    environment:
      - LOAD_CONFIG_PATH=/config/.env.test
      - MAIN_PROCESS=TESTING
      - POSTGRES_DB=rose_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - cache

volumes:
  postgres_data:
  cache:
