# Generated by Django 4.0.7 on 2022-12-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Date")),
                ("start_time", models.DateTimeField(verbose_name="Start Time")),
                ("end_time", models.DateTimeField(blank=True, null=True, verbose_name="End Time")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ParameterSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("status", models.BooleanField(default=False, verbose_name="Status")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddConstraint(
            model_name="parametersettings",
            constraint=models.UniqueConstraint(
                fields=("name", "status"), name="core_parametersettings_unique_parameter_settings"
            ),
        ),
    ]
