# Generated by Django 4.0.7 on 2023-02-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ParameterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('nick_name', models.CharField(max_length=100, verbose_name='Nick Name')),
                ('tag', models.CharField(max_length=20, verbose_name='Tag')),
                ('config_type', models.CharField(choices=[('BOOL', 'Boolean'), ('CHAR', 'String'), ('TEXT', 'Text'), ('FLOAT', 'Float'), ('INT', 'Integer'), ('DATE', 'Date')], max_length=10, verbose_name='Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('content_bool', models.BooleanField(blank=True, null=True, verbose_name='Boolean')),
                ('content_char', models.CharField(blank=True, max_length=100, null=True, verbose_name='Char')),
                ('content_text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('content_float', models.FloatField(blank=True, null=True, verbose_name='Float')),
                ('content_int', models.IntegerField(blank=True, null=True, verbose_name='Integer')),
                ('content_date', models.DateField(blank=True, null=True, verbose_name='Date')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParameterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='parametersettings',
            constraint=models.UniqueConstraint(fields=('name', 'status'), name='core_parametersettings_unique_parameter_settings'),
        ),
        migrations.AddConstraint(
            model_name='parameterconfig',
            constraint=models.UniqueConstraint(fields=('nick_name',), name='core_parameterconfig_unique_parameter_configs'),
        ),
    ]
