# Generated by Django 4.0.7 on 2023-02-26 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParameterSettings',
        ),
        migrations.AlterModelOptions(
            name='parameterconfig',
            options={'ordering': ['tag', 'nick_name']},
        ),
    ]
