# Generated by Django 4.0.7 on 2023-02-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterConfigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('nick_name', models.CharField(max_length=200, verbose_name='Nick Name')),
                ('tag', models.CharField(max_length=200, verbose_name='Tag')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('content', models.CharField(max_length=200, verbose_name='Content')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='parameterconfigs',
            constraint=models.UniqueConstraint(fields=('nick_name',), name='core_parameterconfigs_unique_parameter_configs'),
        ),
    ]
