# Generated by Django 4.0.7 on 2022-09-14 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Configuration",
            new_name="ConfigureSettings",
        ),
    ]
