# Generated by Django 4.0.7 on 2023-02-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_parametersettings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameterconfig',
            options={'ordering': ['tag', 'sequence']},
        ),
        migrations.AddField(
            model_name='parameterconfig',
            name='sequence',
            field=models.IntegerField(default=1, verbose_name='Sequence'),
            preserve_default=False,
        ),
    ]
