# Generated by Django 4.0.7 on 2023-02-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parameterconfigs_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParameterConfigs',
            new_name='ParameterConfig',
        ),
        migrations.RemoveConstraint(
            model_name='parameterconfig',
            name='core_parameterconfigs_unique_parameter_configs',
        ),
        migrations.AddConstraint(
            model_name='parameterconfig',
            constraint=models.UniqueConstraint(fields=('nick_name',), name='core_parameterconfig_unique_parameter_configs'),
        ),
    ]
