# Generated by Django 4.0.7 on 2023-02-05 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_parameterconfigs_parameterconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterconfig',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
