# Generated by Django 4.0.7 on 2023-02-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_parameterconfig_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterconfig',
            name='content',
            field=models.CharField(max_length=255, verbose_name='Content'),
        ),
    ]
