# Generated by Django 4.0.7 on 2023-02-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_parameterconfig_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterconfig',
            name='content',
            field=models.CharField(max_length=300, verbose_name='Content'),
        ),
    ]
