# Generated by Django 4.0.7 on 2022-09-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_configuresettings_string_value_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="configuresettings",
            constraint=models.UniqueConstraint(fields=("name",), name="core_configuresettings_unique"),
        ),
    ]
