# Generated by Django 4.0.7 on 2022-09-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_configuresettings_core_configuresettings_unique"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConfigureSettings",
        ),
    ]
