# Generated by Django 4.0.7 on 2023-01-22 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(verbose_name='Created Date')),
                ('updated_date', models.DateField(verbose_name='Updated Date')),
                ('symbol', models.CharField(max_length=200, verbose_name='Symbol')),
                ('token', models.CharField(blank=True, max_length=50, null=True, verbose_name='Token')),
                ('identifier', models.CharField(max_length=200, verbose_name='Identifier')),
                ('company_name', models.CharField(max_length=500, verbose_name='Company Name')),
                ('isin', models.CharField(max_length=100, verbose_name='Isin')),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='StockMacd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('open', models.FloatField(verbose_name='Open')),
                ('high', models.FloatField(verbose_name='High')),
                ('low', models.FloatField(verbose_name='Low')),
                ('close', models.FloatField(verbose_name='Close')),
                ('volume', models.FloatField(verbose_name='Volume')),
                ('macd', models.FloatField(verbose_name='MACD')),
                ('macd_histogram', models.FloatField(verbose_name='Histogram')),
                ('macd_signal', models.FloatField(verbose_name='Signal')),
                ('buy_signal', models.FloatField(verbose_name='Buy Signal')),
                ('sell_signal', models.FloatField(verbose_name='Sell Signal')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='udipi.stockmaster', verbose_name='Stock')),
            ],
        ),
    ]
