# Generated by Django 4.0.7 on 2023-01-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udipi', '0002_stockmaster_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmaster',
            name='is_error',
            field=models.BooleanField(default=False, verbose_name='Is Error'),
        ),
    ]
