# Generated by Django 4.0.7 on 2022-10-11 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bengaluru', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fhzero',
            options={'ordering': ['symbol']},
        ),
    ]
