# Generated by Django 4.0.7 on 2023-02-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengaluru', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fhzerouptrend',
            name='buy_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Buy Price'),
        ),
        migrations.AlterField(
            model_name='fhzerouptrend',
            name='current_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Current Price'),
        ),
        migrations.AlterField(
            model_name='fhzerouptrend',
            name='high_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Current Price'),
        ),
        migrations.AlterField(
            model_name='fhzerouptrend',
            name='pl_price',
            field=models.FloatField(blank=True, null=True, verbose_name='PL Price'),
        ),
        migrations.AlterField(
            model_name='fhzerouptrend',
            name='sell_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Sell Price'),
        ),
        migrations.AlterField(
            model_name='fhzerouptrend',
            name='trigger_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Current Price'),
        ),
    ]
