# Generated by Django 4.0.7 on 2022-12-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengaluru', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhzerouptrend',
            name='pl_status',
            field=models.CharField(choices=[('WR', 'Winner'), ('RR', 'Runner'), ('IP', 'In-Progress')], default='IP', max_length=2),
        ),
        migrations.AddField(
            model_name='fhzerouptrend',
            name='previous_price',
            field=models.FloatField(default=0, verbose_name='Previous Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fhzerouptrend',
            name='previous_rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='Previous Rank'),
        ),
        migrations.AddField(
            model_name='fhzerouptrend',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='Rank'),
            preserve_default=False,
        ),
    ]
