# Generated by Django 4.0.7 on 2022-10-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengaluru', '0002_alter_fivehundred_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fivehundred',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='Rank'),
            preserve_default=False,
        ),
    ]
