# Generated by Django 4.0.7 on 2023-01-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengaluru', '0002_fhzerouptrend_pl_status_fhzerouptrend_previous_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhzerouptrend',
            name='pl_price',
            field=models.FloatField(default=0.0, verbose_name='PL Price'),
        ),
    ]
