# Generated by Django 4.0.7 on 2023-02-19 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bengaluru', '0002_alter_fhzerouptrend_buy_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fhzerouptrend',
            name='trigger_price',
        ),
    ]
