# Generated by Django 4.0.7 on 2023-01-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bengaluru', '0003_fhzerouptrend_pl_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fhzerouptrend',
            name='previous_price',
        ),
        migrations.RemoveField(
            model_name='fhzerouptrend',
            name='previous_rank',
        ),
    ]
