# Generated by Django 4.0.7 on 2022-12-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengaluru', '0003_fivehundred_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fivehundred',
            name='bar',
            field=models.CharField(blank=True, default='level0', max_length=200, null=True, verbose_name='Bar'),
        ),
    ]
