# Generated by Django 4.0.7 on 2022-10-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bengaluru', '0004_remove_fhzero_order_id_fhzero_buy_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fhzero',
            name='tag',
        ),
    ]
