# Generated by Django 4.0.7 on 2022-09-16 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bengaluru', '0004_fivehundred_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fivehundred',
            name='status',
        ),
    ]
