# Generated by Django 4.0.7 on 2023-01-18 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bengaluru', '0004_remove_fhzerouptrend_previous_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fhzerouptrend',
            name='time',
        ),
        migrations.AddField(
            model_name='fhzerouptrend',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
    ]
