# Generated by Django 4.0.7 on 2022-12-08 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bengaluru', '0004_alter_fivehundred_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='fivehundred',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
    ]
