# Generated by Django 4.0.7 on 2022-10-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bengaluru', '0005_remove_fhzero_tag'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fhzero',
            name='bengaluru_fhzero_unique_tag',
        ),
    ]
