# Generated by Django 4.0.7 on 2023-01-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengaluru', '0005_remove_fhzerouptrend_time_fhzerouptrend_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhzerouptrend',
            name='high_price',
            field=models.FloatField(default=0.0, verbose_name='Current Price'),
        ),
        migrations.AddField(
            model_name='fhzerouptrend',
            name='trigger_price',
            field=models.FloatField(default=0.0, verbose_name='Current Price'),
        ),
    ]
