# Generated by Django 4.0.7 on 2022-09-21 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bengaluru", "0010_alter_fhzero_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fhzero",
            old_name="fh_id",
            new_name="five_hundred",
        ),
    ]
