# Generated by Django 4.0.7 on 2023-02-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopTen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('created_date', models.DateTimeField(verbose_name='Created Date')),
                ('rank', models.IntegerField(verbose_name='Rank')),
                ('symbol', models.CharField(max_length=200, verbose_name='Symbol')),
                ('smart_token', models.CharField(blank=True, max_length=50, null=True, verbose_name='Smart Token')),
                ('ksec_token', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ksec Token')),
                ('identifier', models.CharField(max_length=200, verbose_name='Identifier')),
                ('company_name', models.CharField(max_length=500, verbose_name='Company Name')),
                ('isin', models.CharField(max_length=100, verbose_name='Isin')),
                ('last_price', models.FloatField(verbose_name='Price')),
                ('open_price', models.FloatField(blank=True, null=True, verbose_name='Open Price')),
                ('percentage_change', models.FloatField(verbose_name='Percentage')),
                ('is_valid', models.BooleanField(default=False, verbose_name='Is Valid')),
                ('ema_200', models.FloatField(blank=True, null=True, verbose_name='Ema200')),
                ('last_close', models.FloatField(blank=True, null=True, verbose_name='Last Close')),
                ('day_macd', models.FloatField(blank=True, null=True, verbose_name='MACD')),
                ('day_macd_signal', models.FloatField(blank=True, null=True, verbose_name='MACD Signal')),
                ('day_macd_histogram', models.FloatField(blank=True, null=True, verbose_name='MACD Histogram')),
                ('day_status', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=5)),
                ('macd', models.FloatField(blank=True, null=True, verbose_name='MACD')),
                ('macd_signal', models.FloatField(blank=True, null=True, verbose_name='MACD Signal')),
                ('macd_histogram', models.FloatField(blank=True, null=True, verbose_name='MACD Histogram')),
            ],
            options={
                'ordering': ['-date', 'rank'],
            },
        ),
        migrations.AddConstraint(
            model_name='topten',
            constraint=models.UniqueConstraint(fields=('date', 'symbol'), name='mysuru_topten_unique_five_hundred'),
        ),
    ]
