# Generated by Django 4.2.1 on 2024-06-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysuru", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DailyTrend",
        ),
        migrations.DeleteModel(
            name="HourlyTrend",
        ),
        migrations.DeleteModel(
            name="WeeklyTrend",
        ),
        migrations.AddField(
            model_name="stockdata",
            name="is_trading",
            field=models.BooleanField(default=False, verbose_name="Is Trading"),
        ),
    ]
