# Generated by Django 4.0.7 on 2023-02-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysuru', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topten',
            options={'ordering': ['-date', 'symbol']},
        ),
        migrations.RemoveConstraint(
            model_name='topten',
            name='mysuru_topten_unique_five_hundred',
        ),
        migrations.RemoveField(
            model_name='topten',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='topten',
            name='open_price',
        ),
        migrations.RemoveField(
            model_name='topten',
            name='rank',
        ),
        migrations.AddConstraint(
            model_name='topten',
            constraint=models.UniqueConstraint(fields=('date', 'symbol'), name='mysuru_topten_unique_top_ten'),
        ),
    ]
