# Generated by Django 4.2.1 on 2023-05-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysuru", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TopTen",
        ),
    ]
