# Generated by Django 4.2.1 on 2023-08-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysuru", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stochweeklytrend",
            name="crossed",
            field=models.BooleanField(default=False, verbose_name="Stoch Crossed"),
        ),
    ]
