# Generated by Django 4.0.7 on 2023-01-01 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysuru', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fhzerodowntrend',
            name='time',
        ),
        migrations.AddField(
            model_name='fhzerodowntrend',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
    ]
