# Generated by Django 4.0.7 on 2023-03-14 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysuru', '0002_remove_topten_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topten',
            name='macd_status',
        ),
        migrations.RemoveField(
            model_name='topten',
            name='today_macd',
        ),
        migrations.RemoveField(
            model_name='topten',
            name='today_macd_histogram',
        ),
        migrations.RemoveField(
            model_name='topten',
            name='today_macd_signal',
        ),
        migrations.RemoveField(
            model_name='topten',
            name='today_osc',
        ),
        migrations.RemoveField(
            model_name='topten',
            name='today_osc_signal',
        ),
        migrations.RemoveField(
            model_name='topten',
            name='yesterday_macd',
        ),
        migrations.RemoveField(
            model_name='topten',
            name='yesterday_macd_histogram',
        ),
        migrations.RemoveField(
            model_name='topten',
            name='yesterday_macd_signal',
        ),
        migrations.RemoveField(
            model_name='topten',
            name='yesterday_osc',
        ),
        migrations.RemoveField(
            model_name='topten',
            name='yesterday_osc_signal',
        ),
    ]
