# Generated by Django 4.2.1 on 2023-08-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysuru", "0002_stochweeklytrend_crossed"),
    ]

    operations = [
        migrations.AddField(
            model_name="stochweeklytrend",
            name="tend_to_positive",
            field=models.BooleanField(default=False, verbose_name="Tend to Positive"),
        ),
    ]
