# Generated by Django 4.0.7 on 2023-01-02 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysuru', '0002_remove_fhzerodowntrend_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fhzerodowntrend',
            name='previous_price',
        ),
        migrations.RemoveField(
            model_name='fhzerodowntrend',
            name='previous_rank',
        ),
    ]
