# Generated by Django 4.2.1 on 2024-06-22 23:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysuru', '0002_delete_dailytrend_delete_hourlytrend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='trading_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Trading Updated at'),
            preserve_default=False,
        ),
    ]
