# Generated by Django 4.2.1 on 2024-01-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysuru", "0003_alter_stochdailytrend_company_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stochweeklytrend",
            name="company_name",
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Company Name"),
        ),
        migrations.AlterField(
            model_name="stochweeklytrend",
            name="identifier",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Identifier"),
        ),
        migrations.AlterField(
            model_name="stochweeklytrend",
            name="isin",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Isin"),
        ),
        migrations.AlterField(
            model_name="stochweeklytrend",
            name="percentage_change",
            field=models.FloatField(blank=True, null=True, verbose_name="Percentage"),
        ),
        migrations.AlterField(
            model_name="stochweeklytrend",
            name="price",
            field=models.FloatField(blank=True, null=True, verbose_name="Price"),
        ),
    ]
