# Generated by Django 4.2.1 on 2023-08-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysuru", "0003_stochweeklytrend_tend_to_positive"),
    ]

    operations = [
        migrations.AddField(
            model_name="stochweeklytrend",
            name="d_trend",
            field=models.BooleanField(default=False, verbose_name="D Trend"),
        ),
    ]
