# Generated by Django 4.2.1 on 2023-06-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysuru", "0003_stochdailytrend_stochweeklytrend_delete_stochtrend_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stochdailytrend",
            name="d_value",
            field=models.FloatField(default=0.0, verbose_name="D value"),
        ),
        migrations.AddField(
            model_name="stochweeklytrend",
            name="d_value",
            field=models.FloatField(default=0.0, verbose_name="D value"),
        ),
    ]
