# Generated by Django 4.0.7 on 2023-03-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysuru', '0003_topten_is_accepted_mysurutrend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topten',
            old_name='day_macd',
            new_name='today_macd',
        ),
        migrations.RenameField(
            model_name='topten',
            old_name='day_macd_histogram',
            new_name='today_macd_histogram',
        ),
        migrations.RenameField(
            model_name='topten',
            old_name='day_macd_signal',
            new_name='today_macd_signal',
        ),
        migrations.RenameField(
            model_name='topten',
            old_name='macd',
            new_name='yesterday_macd',
        ),
        migrations.RenameField(
            model_name='topten',
            old_name='macd_histogram',
            new_name='yesterday_macd_histogram',
        ),
        migrations.RenameField(
            model_name='topten',
            old_name='macd_signal',
            new_name='yesterday_macd_signal',
        ),
        migrations.AddField(
            model_name='topten',
            name='ema_50',
            field=models.FloatField(blank=True, null=True, verbose_name='Ema50'),
        ),
    ]
