# Generated by Django 4.0.7 on 2023-01-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysuru', '0003_remove_fhzerodowntrend_previous_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhzerodowntrend',
            name='pl_price',
            field=models.FloatField(default=0.0, verbose_name='PL Price'),
        ),
    ]
