# Generated by Django 4.2.1 on 2024-06-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysuru", "0003_stockdata_trading_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockdata",
            name="trading_updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Trading Updated at"),
        ),
    ]
