# Generated by Django 4.0.7 on 2023-01-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysuru', '0004_fhzerodowntrend_pl_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhzerodowntrend',
            name='high_price',
            field=models.FloatField(default=0.0, verbose_name='Current Price'),
        ),
        migrations.AddField(
            model_name='fhzerodowntrend',
            name='trigger_price',
            field=models.FloatField(default=0.0, verbose_name='Current Price'),
        ),
    ]
