# Generated by Django 4.0.7 on 2023-03-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysuru', '0004_rename_day_macd_topten_today_macd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topten',
            name='today_macd',
        ),
        migrations.RemoveField(
            model_name='topten',
            name='today_macd_histogram',
        ),
        migrations.RemoveField(
            model_name='topten',
            name='today_macd_signal',
        ),
        migrations.RemoveField(
            model_name='topten',
            name='yesterday_macd',
        ),
        migrations.RemoveField(
            model_name='topten',
            name='yesterday_macd_histogram',
        ),
        migrations.RemoveField(
            model_name='topten',
            name='yesterday_macd_signal',
        ),
        migrations.AddField(
            model_name='topten',
            name='today_osc',
            field=models.FloatField(blank=True, null=True, verbose_name='OSC'),
        ),
        migrations.AddField(
            model_name='topten',
            name='today_osc_signal',
            field=models.FloatField(blank=True, null=True, verbose_name='OSC Signal'),
        ),
        migrations.AddField(
            model_name='topten',
            name='yesterday_osc',
            field=models.FloatField(blank=True, null=True, verbose_name='Yesterday OSC'),
        ),
        migrations.AddField(
            model_name='topten',
            name='yesterday_osc_signal',
            field=models.FloatField(blank=True, null=True, verbose_name='Yesterday OSC Signal'),
        ),
        migrations.DeleteModel(
            name='MysuruTrend',
        ),
    ]
