# Generated by Django 4.2.1 on 2024-08-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysuru', '0004_alter_stockdata_trading_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='trading_status',
            field=models.CharField(blank=True, choices=[('up', 'UP'), ('dn', 'Down')], max_length=2, null=True),
        ),
    ]
