# Generated by Django 4.0.7 on 2023-03-15 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysuru", "0005_alter_topten_updated_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topten",
            name="is_accepted",
        ),
    ]
