# Generated by Django 4.0.7 on 2023-03-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysuru', '0005_remove_topten_today_macd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topten',
            name='today_macd',
            field=models.FloatField(blank=True, null=True, verbose_name='MACD'),
        ),
        migrations.AddField(
            model_name='topten',
            name='today_macd_histogram',
            field=models.FloatField(blank=True, null=True, verbose_name='MACD Histogram'),
        ),
        migrations.AddField(
            model_name='topten',
            name='today_macd_signal',
            field=models.FloatField(blank=True, null=True, verbose_name='MACD Signal'),
        ),
        migrations.AddField(
            model_name='topten',
            name='yesterday_macd',
            field=models.FloatField(blank=True, null=True, verbose_name='MACD'),
        ),
        migrations.AddField(
            model_name='topten',
            name='yesterday_macd_histogram',
            field=models.FloatField(blank=True, null=True, verbose_name='MACD Histogram'),
        ),
        migrations.AddField(
            model_name='topten',
            name='yesterday_macd_signal',
            field=models.FloatField(blank=True, null=True, verbose_name='MACD Signal'),
        ),
    ]
