# Generated by Django 4.2.1 on 2024-08-26 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysuru', '0006_stockdata_zero_token_stockdata_zero_token_fetched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='zero_token',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='zero_token_fetched',
        ),
    ]
