# Generated by Django 4.0.7 on 2023-03-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysuru', '0006_topten_today_macd_topten_today_macd_histogram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topten',
            name='yesterday_macd',
            field=models.FloatField(blank=True, null=True, verbose_name='Yesterday MACD'),
        ),
        migrations.AlterField(
            model_name='topten',
            name='yesterday_macd_histogram',
            field=models.FloatField(blank=True, null=True, verbose_name='Yesterday MACD Histogram'),
        ),
        migrations.AlterField(
            model_name='topten',
            name='yesterday_macd_signal',
            field=models.FloatField(blank=True, null=True, verbose_name='Yesterday MACD Signal'),
        ),
    ]
