# Generated by Django 4.0.7 on 2023-03-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysuru", "0006_remove_topten_is_accepted"),
    ]

    operations = [
        migrations.CreateModel(
            name="MacdTrend",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Date")),
                ("updated_date", models.DateField(blank=True, null=True, verbose_name="Updated Date")),
                ("symbol", models.CharField(max_length=200, verbose_name="Symbol")),
                ("smart_token", models.CharField(blank=True, max_length=50, null=True, verbose_name="Smart Token")),
                ("identifier", models.CharField(max_length=200, verbose_name="Identifier")),
                ("company_name", models.CharField(max_length=500, verbose_name="Company Name")),
                ("isin", models.CharField(max_length=100, verbose_name="Isin")),
                ("price", models.FloatField(verbose_name="Price")),
                ("percentage_change", models.FloatField(verbose_name="Percentage")),
                ("ema_200", models.FloatField(blank=True, null=True, verbose_name="Ema200")),
                ("ema_50", models.FloatField(blank=True, null=True, verbose_name="Ema50")),
                ("last_close", models.FloatField(blank=True, null=True, verbose_name="Last Close")),
                ("is_valid", models.BooleanField(default=False, verbose_name="Is Valid")),
                ("trend_status", models.CharField(choices=[("YES", "Yes"), ("NO", "No")], default="NO", max_length=5)),
            ],
            options={
                "ordering": ["-date", "symbol"],
            },
        ),
        migrations.RenameField(
            model_name="topten",
            old_name="last_price",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="topten",
            old_name="day_status",
            new_name="trend_status",
        ),
        migrations.RemoveField(
            model_name="topten",
            name="ksec_token",
        ),
        migrations.RemoveField(
            model_name="topten",
            name="osc_status",
        ),
        migrations.AddField(
            model_name="topten",
            name="is_valid",
            field=models.BooleanField(default=False, verbose_name="Is Valid"),
        ),
        migrations.AddConstraint(
            model_name="macdtrend",
            constraint=models.UniqueConstraint(fields=("date", "symbol"), name="mysuru_macdtrend_unique_macd_trend"),
        ),
    ]
