# Generated by Django 4.0.7 on 2023-05-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysuru", "0007_macdtrend_rename_last_price_topten_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("symbol", models.CharField(max_length=200, verbose_name="Symbol")),
                ("smart_token", models.CharField(blank=True, max_length=50, null=True, verbose_name="Smart Token")),
                ("identifier", models.CharField(max_length=200, verbose_name="Identifier")),
                ("company_name", models.CharField(max_length=500, verbose_name="Company Name")),
                ("price_data", models.JSONField(blank=True, null=True, verbose_name="Price Data")),
            ],
            options={
                "ordering": ["symbol"],
            },
        ),
        migrations.AddField(
            model_name="macdtrend",
            name="day_1_status",
            field=models.BooleanField(default=False, verbose_name="Day 1"),
        ),
        migrations.AddField(
            model_name="macdtrend",
            name="day_2_status",
            field=models.BooleanField(default=False, verbose_name="Day 2"),
        ),
        migrations.AddConstraint(
            model_name="priceaction",
            constraint=models.UniqueConstraint(fields=("symbol",), name="mysuru_priceaction_price_action"),
        ),
    ]
