# Generated by Django 4.2.1 on 2024-11-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysuru", "0007_remove_stockdata_zero_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockdata",
            name="day_ema_5_0",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="day_ema_5_1",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="day_ema_5_2",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="day_ema_5_3",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="day_ema_5_4",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="day_ema_5_5",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="hr_ema_5_0",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="hr_ema_5_1",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="hr_ema_5_2",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="hr_ema_5_3",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="hr_ema_5_4",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="hr_ema_5_5",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m15_ema_5_0",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m15_ema_5_1",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m15_ema_5_2",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m15_ema_5_3",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m15_ema_5_4",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m15_ema_5_5",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m5_ema_5_0",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m5_ema_5_1",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m5_ema_5_2",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m5_ema_5_3",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m5_ema_5_4",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m5_ema_5_5",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="wk_ema_5_0",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="wk_ema_5_1",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="wk_ema_5_2",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="wk_ema_5_3",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 20"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="wk_ema_5_4",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="wk_ema_5_5",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 5"),
        ),
    ]
