# Generated by Django 4.0.7 on 2023-03-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysuru', '0007_alter_topten_yesterday_macd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topten',
            name='macd_status',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=5),
        ),
        migrations.AddField(
            model_name='topten',
            name='osc_status',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=5),
        ),
    ]
