# Generated by Django 4.0.7 on 2023-05-06 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysuru', '0008_priceaction_macdtrend_day_1_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macdtrend',
            name='is_valid',
        ),
    ]
