# Generated by Django 4.2.1 on 2024-12-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysuru", "0008_stockdata_day_ema_5_0_stockdata_day_ema_5_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockdata",
            name="day_ema_14_0",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="day_ema_14_1",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="day_ema_14_2",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="day_ema_14_3",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="day_ema_14_4",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="day_ema_14_5",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="hr_ema_14_0",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="hr_ema_14_1",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="hr_ema_14_2",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="hr_ema_14_3",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="hr_ema_14_4",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="hr_ema_14_5",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m15_ema_14_0",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m15_ema_14_1",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m15_ema_14_2",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m15_ema_14_3",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m15_ema_14_4",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m15_ema_14_5",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m5_ema_14_0",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m5_ema_14_1",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m5_ema_14_2",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m5_ema_14_3",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m5_ema_14_4",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m5_ema_14_5",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="wk_ema_14_0",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="wk_ema_14_1",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="wk_ema_14_2",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="wk_ema_14_3",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="wk_ema_14_4",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="wk_ema_14_5",
            field=models.FloatField(blank=True, null=True, verbose_name="EMA 14"),
        ),
    ]
