# Generated by Django 4.0.7 on 2023-05-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysuru", "0009_remove_macdtrend_is_valid"),
    ]

    operations = [
        migrations.AddField(
            model_name="macdtrend",
            name="ema_200_percentage",
            field=models.FloatField(default=0.0, verbose_name="Ema 200 Percentage"),
        ),
    ]
