# Generated by Django 4.2.1 on 2024-02-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysuru', '0009_stochdailytrend_ha_positive'),
    ]

    operations = [
        migrations.CreateModel(
            name='StochHourlyTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('updated_date', models.DateField(blank=True, null=True, verbose_name='Updated Date')),
                ('symbol', models.CharField(max_length=200, verbose_name='Symbol')),
                ('smart_token', models.CharField(blank=True, max_length=50, null=True, verbose_name='Smart Token')),
                ('identifier', models.CharField(blank=True, max_length=200, null=True, verbose_name='Identifier')),
                ('company_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Company Name')),
                ('isin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Isin')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price')),
                ('percentage_change', models.FloatField(blank=True, null=True, verbose_name='Percentage')),
                ('ema_200', models.FloatField(blank=True, null=True, verbose_name='Ema200')),
                ('ema_50', models.FloatField(blank=True, null=True, verbose_name='Ema50')),
                ('last_close', models.FloatField(blank=True, null=True, verbose_name='Last Close')),
                ('stoch_status', models.BooleanField(default=False, verbose_name='Stoch Status')),
                ('stoch_positive_trend', models.BooleanField(default=False, verbose_name='Stoch Positive Trend')),
                ('ema_200_percentage', models.FloatField(default=0.0, verbose_name='Ema 200 Percentage')),
                ('d_value', models.FloatField(default=0.0, verbose_name='D value')),
                ('crossed', models.BooleanField(default=False, verbose_name='Stoch Crossed')),
                ('trend_status', models.BooleanField(default=False, verbose_name='Trend Status')),
                ('ha_positive', models.BooleanField(default=False, verbose_name='Heikin-Ashi Positive')),
                ('ha_cross_yesterday', models.BooleanField(default=False, verbose_name='Heikin-Ashi Crossed Yesterday')),
                ('ha_cross', models.BooleanField(default=False, verbose_name='Heikin-Ashi Crossed Yesterday')),
                ('ha_wma_cross_yesterday', models.BooleanField(default=False, verbose_name='Heikin-Ashi WMA Crossed Yesterday')),
                ('ha_wma_cross', models.BooleanField(default=False, verbose_name='Heikin-Ashi WMA Crossed')),
                ('ha_wma_top', models.BooleanField(default=False, verbose_name='Heikin-Ashi WMA Top')),
            ],
            options={
                'ordering': ['-date', 'symbol'],
            },
        ),
        migrations.AddConstraint(
            model_name='stochhourlytrend',
            constraint=models.UniqueConstraint(fields=('date', 'symbol'), name='mysuru_stochhourlytrend_unique_stoch_trend'),
        ),
    ]
