# Generated by Django 4.2.1 on 2025-01-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysuru", "0009_stockdata_day_ema_14_0_stockdata_day_ema_14_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockdata",
            name="day_close_0",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="day_close_1",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="day_close_2",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="day_close_3",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="day_close_4",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="day_close_5",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="hr_close_0",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="hr_close_1",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="hr_close_2",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="hr_close_3",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="hr_close_4",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="hr_close_5",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m15_close_0",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m15_close_1",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m15_close_2",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m15_close_3",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m15_close_4",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m15_close_5",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m5_close_0",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m5_close_1",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m5_close_2",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m5_close_3",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m5_close_4",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="m5_close_5",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="wk_close_0",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="wk_close_1",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="wk_close_2",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="wk_close_3",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="wk_close_4",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
        migrations.AddField(
            model_name="stockdata",
            name="wk_close_5",
            field=models.FloatField(blank=True, null=True, verbose_name="Close"),
        ),
    ]
