# Generated by Django 4.2.1 on 2025-03-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysuru', '0010_stockdata_day_close_0_stockdata_day_close_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='day_rev_rsi',
            field=models.FloatField(blank=True, null=True, verbose_name='Reverse RSI'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='hr_rev_rsi',
            field=models.FloatField(blank=True, null=True, verbose_name='Reverse RSI'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='m15_rev_rsi',
            field=models.FloatField(blank=True, null=True, verbose_name='Reverse RSI'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='m5_rev_rsi',
            field=models.FloatField(blank=True, null=True, verbose_name='Reverse RSI'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='wk_rev_rsi',
            field=models.FloatField(blank=True, null=True, verbose_name='Reverse RSI'),
        ),
    ]
