# Generated by Django 4.2.1 on 2024-02-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysuru", "0010_stochhourlytrend_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stochhourlytrend",
            name="ha_cross_yesterday",
        ),
        migrations.RemoveField(
            model_name="stochhourlytrend",
            name="ha_wma_cross_yesterday",
        ),
        migrations.AddField(
            model_name="stochhourlytrend",
            name="ha_cross_last_hour",
            field=models.BooleanField(default=False, verbose_name="Heikin-Ashi Crossed Last Hour"),
        ),
        migrations.AddField(
            model_name="stochhourlytrend",
            name="ha_wma_cross_last_hour",
            field=models.BooleanField(default=False, verbose_name="Heikin-Ashi WMA Crossed Last Hour"),
        ),
    ]
