# Generated by Django 4.2.1 on 2025-04-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysuru', '0011_stockdata_day_rev_rsi_stockdata_hr_rev_rsi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdata',
            old_name='day_rev_rsi',
            new_name='day_rev_rsi_40',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='hr_rev_rsi',
            new_name='day_rev_rsi_50',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='m15_rev_rsi',
            new_name='day_rev_rsi_60',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='m5_rev_rsi',
            new_name='hr_rev_rsi_40',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='wk_rev_rsi',
            new_name='hr_rev_rsi_50',
        ),
        migrations.AddField(
            model_name='stockdata',
            name='hr_rev_rsi_60',
            field=models.FloatField(blank=True, null=True, verbose_name='Reverse RSI'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='m15_rev_rsi_40',
            field=models.FloatField(blank=True, null=True, verbose_name='Reverse RSI'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='m15_rev_rsi_50',
            field=models.FloatField(blank=True, null=True, verbose_name='Reverse RSI'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='m15_rev_rsi_60',
            field=models.FloatField(blank=True, null=True, verbose_name='Reverse RSI'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='m5_rev_rsi_40',
            field=models.FloatField(blank=True, null=True, verbose_name='Reverse RSI'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='m5_rev_rsi_50',
            field=models.FloatField(blank=True, null=True, verbose_name='Reverse RSI'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='m5_rev_rsi_60',
            field=models.FloatField(blank=True, null=True, verbose_name='Reverse RSI'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='wk_rev_rsi_40',
            field=models.FloatField(blank=True, null=True, verbose_name='Reverse RSI'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='wk_rev_rsi_50',
            field=models.FloatField(blank=True, null=True, verbose_name='Reverse RSI'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='wk_rev_rsi_60',
            field=models.FloatField(blank=True, null=True, verbose_name='Reverse RSI'),
        ),
    ]
