# Generated by Django 4.2.1 on 2024-03-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysuru', '0013_dailytrend_hourlytrend_weeklytrend_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailytrend',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hourlytrend',
            options={},
        ),
        migrations.AlterModelOptions(
            name='weeklytrend',
            options={},
        ),
        migrations.AlterField(
            model_name='dailytrend',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='dailytrend',
            name='updated_date',
            field=models.DateField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='hourlytrend',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='hourlytrend',
            name='updated_date',
            field=models.DateField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='weeklytrend',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='weeklytrend',
            name='updated_date',
            field=models.DateField(auto_now=True, verbose_name='Updated Date'),
        ),
    ]
