# Generated by Django 4.2.1 on 2024-03-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysuru', '0014_alter_dailytrend_options_alter_hourlytrend_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytrend',
            name='volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Volume'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Volume'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='dailytrend',
            name='stoch_black',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Black'),
        ),
        migrations.AlterField(
            model_name='hourlytrend',
            name='stoch_black',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Black'),
        ),
        migrations.AlterField(
            model_name='weeklytrend',
            name='stoch_black',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Black'),
        ),
    ]
