# Generated by Django 4.2.1 on 2024-03-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysuru', '0015_dailytrend_volume_hourlytrend_volume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytrend',
            name='smart_token_not_found',
        ),
        migrations.RemoveField(
            model_name='hourlytrend',
            name='smart_token_not_found',
        ),
        migrations.RemoveField(
            model_name='weeklytrend',
            name='smart_token_not_found',
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='smart_token_fetched',
            field=models.BooleanField(default=False, verbose_name='Smart Token Fetched'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='smart_token_fetched',
            field=models.BooleanField(default=False, verbose_name='Smart Token Fetched'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='smart_token_fetched',
            field=models.BooleanField(default=False, verbose_name='Smart Token Fetched'),
        ),
    ]
