# Generated by Django 4.2.1 on 2024-03-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysuru', '0016_remove_dailytrend_smart_token_not_found_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytrend',
            name='is_fetched',
            field=models.BooleanField(default=False, verbose_name='Is Fetched'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='is_fetched',
            field=models.BooleanField(default=False, verbose_name='Is Fetched'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='is_fetched',
            field=models.BooleanField(default=False, verbose_name='Is Fetched'),
        ),
    ]
