# Generated by Django 4.2.1 on 2024-05-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysuru', '0017_dailytrend_is_fetched_hourlytrend_is_fetched_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailytrend',
            old_name='ha_close',
            new_name='ha_close_0',
        ),
        migrations.RenameField(
            model_name='dailytrend',
            old_name='ha_high',
            new_name='ha_high_0',
        ),
        migrations.RenameField(
            model_name='dailytrend',
            old_name='ha_low',
            new_name='ha_low_0',
        ),
        migrations.RenameField(
            model_name='dailytrend',
            old_name='ha_open',
            new_name='ha_open_0',
        ),
        migrations.RenameField(
            model_name='dailytrend',
            old_name='rsi',
            new_name='rsi_0',
        ),
        migrations.RenameField(
            model_name='dailytrend',
            old_name='stoch_black',
            new_name='stoch_black_0',
        ),
        migrations.RenameField(
            model_name='dailytrend',
            old_name='stoch_red',
            new_name='stoch_red_0',
        ),
        migrations.RenameField(
            model_name='hourlytrend',
            old_name='ha_close',
            new_name='ha_close_0',
        ),
        migrations.RenameField(
            model_name='hourlytrend',
            old_name='ha_high',
            new_name='ha_high_0',
        ),
        migrations.RenameField(
            model_name='hourlytrend',
            old_name='ha_low',
            new_name='ha_low_0',
        ),
        migrations.RenameField(
            model_name='hourlytrend',
            old_name='ha_open',
            new_name='ha_open_0',
        ),
        migrations.RenameField(
            model_name='hourlytrend',
            old_name='rsi',
            new_name='rsi_0',
        ),
        migrations.RenameField(
            model_name='hourlytrend',
            old_name='stoch_black',
            new_name='stoch_black_0',
        ),
        migrations.RenameField(
            model_name='hourlytrend',
            old_name='stoch_red',
            new_name='stoch_red_0',
        ),
        migrations.RenameField(
            model_name='weeklytrend',
            old_name='ha_close',
            new_name='ha_close_0',
        ),
        migrations.RenameField(
            model_name='weeklytrend',
            old_name='ha_high',
            new_name='ha_high_0',
        ),
        migrations.RenameField(
            model_name='weeklytrend',
            old_name='ha_low',
            new_name='ha_low_0',
        ),
        migrations.RenameField(
            model_name='weeklytrend',
            old_name='ha_open',
            new_name='ha_open_0',
        ),
        migrations.RenameField(
            model_name='weeklytrend',
            old_name='rsi',
            new_name='rsi_0',
        ),
        migrations.RenameField(
            model_name='weeklytrend',
            old_name='stoch_black',
            new_name='stoch_black_0',
        ),
        migrations.RenameField(
            model_name='weeklytrend',
            old_name='stoch_red',
            new_name='stoch_red_0',
        ),
        migrations.RemoveField(
            model_name='dailytrend',
            name='ha_close_previous',
        ),
        migrations.RemoveField(
            model_name='dailytrend',
            name='ha_high_previous',
        ),
        migrations.RemoveField(
            model_name='dailytrend',
            name='ha_low_previous',
        ),
        migrations.RemoveField(
            model_name='dailytrend',
            name='ha_open_previous',
        ),
        migrations.RemoveField(
            model_name='dailytrend',
            name='rsi_previous',
        ),
        migrations.RemoveField(
            model_name='dailytrend',
            name='stoch_black_previous',
        ),
        migrations.RemoveField(
            model_name='dailytrend',
            name='stoch_red_previous',
        ),
        migrations.RemoveField(
            model_name='hourlytrend',
            name='ha_close_previous',
        ),
        migrations.RemoveField(
            model_name='hourlytrend',
            name='ha_high_previous',
        ),
        migrations.RemoveField(
            model_name='hourlytrend',
            name='ha_low_previous',
        ),
        migrations.RemoveField(
            model_name='hourlytrend',
            name='ha_open_previous',
        ),
        migrations.RemoveField(
            model_name='hourlytrend',
            name='rsi_previous',
        ),
        migrations.RemoveField(
            model_name='hourlytrend',
            name='stoch_black_previous',
        ),
        migrations.RemoveField(
            model_name='hourlytrend',
            name='stoch_red_previous',
        ),
        migrations.RemoveField(
            model_name='weeklytrend',
            name='ha_close_previous',
        ),
        migrations.RemoveField(
            model_name='weeklytrend',
            name='ha_high_previous',
        ),
        migrations.RemoveField(
            model_name='weeklytrend',
            name='ha_low_previous',
        ),
        migrations.RemoveField(
            model_name='weeklytrend',
            name='ha_open_previous',
        ),
        migrations.RemoveField(
            model_name='weeklytrend',
            name='rsi_previous',
        ),
        migrations.RemoveField(
            model_name='weeklytrend',
            name='stoch_black_previous',
        ),
        migrations.RemoveField(
            model_name='weeklytrend',
            name='stoch_red_previous',
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ha_close_1',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Close'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ha_close_2',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Close'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ha_close_3',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Close'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ha_close_4',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Close'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ha_close_5',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Close'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ha_high_1',
            field=models.FloatField(blank=True, null=True, verbose_name='HA High'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ha_high_2',
            field=models.FloatField(blank=True, null=True, verbose_name='HA High'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ha_high_3',
            field=models.FloatField(blank=True, null=True, verbose_name='HA High'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ha_high_4',
            field=models.FloatField(blank=True, null=True, verbose_name='HA High'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ha_high_5',
            field=models.FloatField(blank=True, null=True, verbose_name='HA High'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ha_low_1',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Low'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ha_low_2',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Low'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ha_low_3',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Low'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ha_low_4',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Low'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ha_low_5',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Low'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ha_open_1',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Open'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ha_open_2',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Open'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ha_open_3',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Open'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ha_open_4',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Open'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ha_open_5',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Open'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='rsi_1',
            field=models.FloatField(blank=True, null=True, verbose_name='RSI'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='rsi_2',
            field=models.FloatField(blank=True, null=True, verbose_name='RSI'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='rsi_3',
            field=models.FloatField(blank=True, null=True, verbose_name='RSI'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='rsi_4',
            field=models.FloatField(blank=True, null=True, verbose_name='RSI'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='rsi_5',
            field=models.FloatField(blank=True, null=True, verbose_name='RSI'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='stoch_black_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Black'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='stoch_black_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Black'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='stoch_black_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Black'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='stoch_black_4',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Black'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='stoch_black_5',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Black'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='stoch_red_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Red'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='stoch_red_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Red'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='stoch_red_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Red'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='stoch_red_4',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Red'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='stoch_red_5',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Red'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ha_close_1',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Close'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ha_close_2',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Close'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ha_close_3',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Close'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ha_close_4',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Close'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ha_close_5',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Close'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ha_high_1',
            field=models.FloatField(blank=True, null=True, verbose_name='HA High'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ha_high_2',
            field=models.FloatField(blank=True, null=True, verbose_name='HA High'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ha_high_3',
            field=models.FloatField(blank=True, null=True, verbose_name='HA High'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ha_high_4',
            field=models.FloatField(blank=True, null=True, verbose_name='HA High'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ha_high_5',
            field=models.FloatField(blank=True, null=True, verbose_name='HA High'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ha_low_1',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Low'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ha_low_2',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Low'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ha_low_3',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Low'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ha_low_4',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Low'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ha_low_5',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Low'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ha_open_1',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Open'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ha_open_2',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Open'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ha_open_3',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Open'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ha_open_4',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Open'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ha_open_5',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Open'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='rsi_1',
            field=models.FloatField(blank=True, null=True, verbose_name='RSI'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='rsi_2',
            field=models.FloatField(blank=True, null=True, verbose_name='RSI'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='rsi_3',
            field=models.FloatField(blank=True, null=True, verbose_name='RSI'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='rsi_4',
            field=models.FloatField(blank=True, null=True, verbose_name='RSI'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='rsi_5',
            field=models.FloatField(blank=True, null=True, verbose_name='RSI'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='stoch_black_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Black'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='stoch_black_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Black'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='stoch_black_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Black'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='stoch_black_4',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Black'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='stoch_black_5',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Black'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='stoch_red_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Red'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='stoch_red_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Red'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='stoch_red_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Red'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='stoch_red_4',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Red'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='stoch_red_5',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Red'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ha_close_1',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Close'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ha_close_2',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Close'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ha_close_3',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Close'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ha_close_4',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Close'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ha_close_5',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Close'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ha_high_1',
            field=models.FloatField(blank=True, null=True, verbose_name='HA High'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ha_high_2',
            field=models.FloatField(blank=True, null=True, verbose_name='HA High'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ha_high_3',
            field=models.FloatField(blank=True, null=True, verbose_name='HA High'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ha_high_4',
            field=models.FloatField(blank=True, null=True, verbose_name='HA High'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ha_high_5',
            field=models.FloatField(blank=True, null=True, verbose_name='HA High'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ha_low_1',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Low'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ha_low_2',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Low'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ha_low_3',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Low'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ha_low_4',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Low'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ha_low_5',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Low'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ha_open_1',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Open'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ha_open_2',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Open'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ha_open_3',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Open'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ha_open_4',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Open'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ha_open_5',
            field=models.FloatField(blank=True, null=True, verbose_name='HA Open'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='rsi_1',
            field=models.FloatField(blank=True, null=True, verbose_name='RSI'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='rsi_2',
            field=models.FloatField(blank=True, null=True, verbose_name='RSI'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='rsi_3',
            field=models.FloatField(blank=True, null=True, verbose_name='RSI'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='rsi_4',
            field=models.FloatField(blank=True, null=True, verbose_name='RSI'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='rsi_5',
            field=models.FloatField(blank=True, null=True, verbose_name='RSI'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='stoch_black_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Black'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='stoch_black_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Black'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='stoch_black_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Black'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='stoch_black_4',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Black'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='stoch_black_5',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Black'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='stoch_red_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Red'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='stoch_red_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Red'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='stoch_red_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Red'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='stoch_red_4',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Red'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='stoch_red_5',
            field=models.FloatField(blank=True, null=True, verbose_name='Stoch Red'),
        ),
    ]
