# Generated by Django 4.2.1 on 2024-05-05 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysuru', '0018_rename_ha_close_dailytrend_ha_close_0_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StochDailyTrend',
        ),
        migrations.DeleteModel(
            name='StochHourlyTrend',
        ),
        migrations.DeleteModel(
            name='StochWeeklyTrend',
        ),
    ]
