# Generated by Django 4.2.1 on 2024-05-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysuru', '0019_delete_stochdailytrend_delete_stochhourlytrend_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailytrend',
            old_name='ema_200',
            new_name='ema_200_0',
        ),
        migrations.RenameField(
            model_name='dailytrend',
            old_name='ema_200_percentage',
            new_name='ema_200_percentage_0',
        ),
        migrations.RenameField(
            model_name='dailytrend',
            old_name='ema_20',
            new_name='ema_20_0',
        ),
        migrations.RenameField(
            model_name='dailytrend',
            old_name='ema_50',
            new_name='ema_50_0',
        ),
        migrations.RenameField(
            model_name='hourlytrend',
            old_name='ema_200',
            new_name='ema_200_0',
        ),
        migrations.RenameField(
            model_name='hourlytrend',
            old_name='ema_200_percentage',
            new_name='ema_200_percentage_0',
        ),
        migrations.RenameField(
            model_name='hourlytrend',
            old_name='ema_20',
            new_name='ema_20_0',
        ),
        migrations.RenameField(
            model_name='hourlytrend',
            old_name='ema_50',
            new_name='ema_50_0',
        ),
        migrations.RenameField(
            model_name='weeklytrend',
            old_name='ema_200',
            new_name='ema_200_0',
        ),
        migrations.RenameField(
            model_name='weeklytrend',
            old_name='ema_200_percentage',
            new_name='ema_200_percentage_0',
        ),
        migrations.RenameField(
            model_name='weeklytrend',
            old_name='ema_20',
            new_name='ema_20_0',
        ),
        migrations.RenameField(
            model_name='weeklytrend',
            old_name='ema_50',
            new_name='ema_50_0',
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ema_200_1',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ema_200_2',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ema_200_3',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ema_200_4',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ema_200_5',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ema_200_percentage_1',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200 Percentage'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ema_200_percentage_2',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200 Percentage'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ema_200_percentage_3',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200 Percentage'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ema_200_percentage_4',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200 Percentage'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ema_200_percentage_5',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200 Percentage'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ema_20_1',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 20'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ema_20_2',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 20'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ema_20_3',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 20'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ema_20_4',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 20'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ema_20_5',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 20'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ema_50_1',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 50'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ema_50_2',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 50'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ema_50_3',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 50'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ema_50_4',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 50'),
        ),
        migrations.AddField(
            model_name='dailytrend',
            name='ema_50_5',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 50'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ema_200_1',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ema_200_2',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ema_200_3',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ema_200_4',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ema_200_5',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ema_200_percentage_1',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200 Percentage'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ema_200_percentage_2',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200 Percentage'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ema_200_percentage_3',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200 Percentage'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ema_200_percentage_4',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200 Percentage'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ema_200_percentage_5',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200 Percentage'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ema_20_1',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 20'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ema_20_2',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 20'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ema_20_3',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 20'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ema_20_4',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 20'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ema_20_5',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 20'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ema_50_1',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 50'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ema_50_2',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 50'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ema_50_3',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 50'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ema_50_4',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 50'),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ema_50_5',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 50'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ema_200_1',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ema_200_2',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ema_200_3',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ema_200_4',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ema_200_5',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ema_200_percentage_1',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200 Percentage'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ema_200_percentage_2',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200 Percentage'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ema_200_percentage_3',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200 Percentage'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ema_200_percentage_4',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200 Percentage'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ema_200_percentage_5',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 200 Percentage'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ema_20_1',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 20'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ema_20_2',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 20'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ema_20_3',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 20'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ema_20_4',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 20'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ema_20_5',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 20'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ema_50_1',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 50'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ema_50_2',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 50'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ema_50_3',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 50'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ema_50_4',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 50'),
        ),
        migrations.AddField(
            model_name='weeklytrend',
            name='ema_50_5',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA 50'),
        ),
    ]
