# Generated by Django 4.0.7 on 2023-02-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiveHundred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('created_date', models.DateTimeField(verbose_name='Created Date')),
                ('rank', models.IntegerField(verbose_name='Rank')),
                ('symbol', models.CharField(max_length=200, verbose_name='Symbol')),
                ('smart_token', models.CharField(blank=True, max_length=50, null=True, verbose_name='Smart Token')),
                ('ksec_token', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ksec Token')),
                ('identifier', models.CharField(max_length=200, verbose_name='Identifier')),
                ('company_name', models.CharField(max_length=500, verbose_name='Company Name')),
                ('isin', models.CharField(max_length=100, verbose_name='Isin')),
                ('last_price', models.FloatField(verbose_name='Price')),
                ('open_price', models.FloatField(blank=True, null=True, verbose_name='Open Price')),
                ('percentage_change', models.FloatField(verbose_name='Percentage')),
                ('signal_status', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('IP', 'In-Progress')], default='IP', max_length=5)),
                ('is_valid', models.BooleanField(default=False, verbose_name='Is Valid')),
                ('pp2', models.FloatField(blank=True, null=True, verbose_name='PP2')),
                ('pp1', models.FloatField(blank=True, null=True, verbose_name='PP1')),
                ('pp', models.FloatField(blank=True, null=True, verbose_name='PP0')),
                ('pp_price', models.FloatField(blank=True, null=True, verbose_name='PP0 Price')),
                ('pp1_price', models.FloatField(blank=True, null=True, verbose_name='PP1 Price')),
                ('pp2_price', models.FloatField(blank=True, null=True, verbose_name='PP2 Price')),
            ],
            options={
                'ordering': ['-date', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='StockWatchFh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('created_date', models.DateTimeField(verbose_name='Created Date')),
                ('stock_data', models.JSONField(blank=True, null=True, verbose_name='Stock Data')),
            ],
        ),
        migrations.AddConstraint(
            model_name='fivehundred',
            constraint=models.UniqueConstraint(fields=('date', 'symbol'), name='stockwatch_fivehundred_unique_five_hundred'),
        ),
    ]
