# Generated by Django 4.0.7 on 2022-12-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockwatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockWatchFh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('created_date', models.DateTimeField(verbose_name='Created Date')),
                ('uid', models.IntegerField(verbose_name='UID')),
                ('rank', models.IntegerField(verbose_name='Rank')),
                ('symbol', models.CharField(max_length=200, verbose_name='Symbol')),
                ('identifier', models.CharField(max_length=200, verbose_name='Identifier')),
                ('company_name', models.CharField(max_length=500, verbose_name='Company Name')),
                ('isin', models.CharField(max_length=100, verbose_name='Isin')),
                ('last_price', models.FloatField(verbose_name='Price')),
                ('percentage_change', models.FloatField(verbose_name='Percentage')),
            ],
        ),
    ]
