# Generated by Django 4.0.7 on 2023-02-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockwatch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fivehundred',
            name='token',
        ),
        migrations.AddField(
            model_name='fivehundred',
            name='ksec_token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ksec Token'),
        ),
        migrations.AddField(
            model_name='fivehundred',
            name='smart_token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Smart Token'),
        ),
    ]
