# Generated by Django 4.0.7 on 2023-02-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockwatch', '0002_remove_fivehundred_token_fivehundred_ksec_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fivehundred',
            name='pp1_price',
            field=models.FloatField(blank=True, null=True, verbose_name='PP1 Price'),
        ),
        migrations.AddField(
            model_name='fivehundred',
            name='pp2_price',
            field=models.FloatField(blank=True, null=True, verbose_name='PP2 Price'),
        ),
        migrations.AddField(
            model_name='fivehundred',
            name='pp_price',
            field=models.FloatField(blank=True, null=True, verbose_name='PP0 Price'),
        ),
    ]
