# Generated by Django 4.0.7 on 2023-01-01 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockwatch', '0005_fivehundred_signal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fivehundred',
            name='highest_rank',
        ),
        migrations.RemoveField(
            model_name='fivehundred',
            name='lowest_rank',
        ),
        migrations.RemoveField(
            model_name='fivehundred',
            name='previous_price',
        ),
        migrations.RemoveField(
            model_name='fivehundred',
            name='previous_price_20min',
        ),
        migrations.RemoveField(
            model_name='fivehundred',
            name='previous_rank',
        ),
        migrations.RemoveField(
            model_name='fivehundred',
            name='time',
        ),
    ]
