# Generated by Django 4.0.7 on 2023-01-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockwatch', '0006_remove_fivehundred_highest_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fivehundred',
            name='open_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Open Price'),
        ),
        migrations.AddField(
            model_name='fivehundred',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Token'),
        ),
    ]
