# Generated by Django 4.0.7 on 2023-01-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockwatch', '0007_fivehundred_open_price_fivehundred_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='fivehundred',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='Is Valid'),
        ),
    ]
