# Generated by Django 4.0.7 on 2023-01-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockwatch', '0008_fivehundred_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='fivehundred',
            name='pp',
            field=models.FloatField(blank=True, null=True, verbose_name='PP0'),
        ),
        migrations.AddField(
            model_name='fivehundred',
            name='pp1',
            field=models.FloatField(blank=True, null=True, verbose_name='PP1'),
        ),
        migrations.AddField(
            model_name='fivehundred',
            name='pp2',
            field=models.FloatField(blank=True, null=True, verbose_name='PP2'),
        ),
    ]
