LOG_SCHEDULE_LIVE_500 = ""
LOG_SCHEDULE_ZERO_500 = ""

SETTINGS_FH_LIVE_STOCKS_NSE = "SETTINGS_FH_LIVE_STOCKS_NSE"
SETTINGS_FHZ_UPTREND = "SETTINGS_FHZ_UPTREND"
SETTINGS_FHZ_DOWNTREND = "SETTINGS_FHZ_DOWNTREND"

LIVE_START = "0935"  # 0935
LIVE_END = "1450"  # 1450
