LOG_SCHEDULE_LIVE_500 = "Live 500"
LOG_SCHEDULE_ZERO_500 = "Zero"

SETTINGS_FH_LIVE_STOCKS_NSE = "SETTINGS_FH_LIVE_STOCKS_NSE"
SETTINGS_FHZ_UPTREND = "SETTINGS_FHZ_UPTREND"
SETTINGS_FHZ_DOWNTREND = "SETTINGS_FHZ_DOWNTREND"
