FH_RANK_FROM: int = 1  # 1
FH_RANK_TILL: int = 4  # 5
FH_GRACE_RANK: int = 1  # 2
FH_MIN_PRICE: int = 20  # 20
FH_MAX_PRICE: int = 4500  # 4500
FH_MAX_TOTAL_PRICE = 5000  # 20000
FH_MAX_PERCENT: int = 11  # 11
FH_MAX_BUY_ORDER: int = 1  # 2


MYSURU_START = "1100"  # 0935
MYSURU_END = "1350"  # 1350


MYSURU_CONFIGURATION = {
    "display_name": "Mysuru",
    "value": {
        "FH_RANK_FROM": FH_RANK_FROM,
        "FH_RANK_TILL": FH_RANK_TILL,
        "FH_GRACE_RANK": FH_GRACE_RANK,
        "FH_MIN_PRICE": FH_MIN_PRICE,
        "FH_MAX_PRICE": FH_MAX_PRICE,
        "FH_MAX_TOTAL_PRICE": FH_MAX_TOTAL_PRICE,
        "FH_MAX_PERCENT": FH_MAX_PERCENT,
        "FH_MAX_BUY_ORDER": FH_MAX_BUY_ORDER,
    },
}
