from datetime import datetime, time

import pandas as pd
from dateutil.relativedelta import relativedelta
from django.db import models
from datetime import timedelta

from core.smart_util import SmartInstrument, SmartTool
from core.tools import (
    calculate_stochastic,
    get_param_config_tag,
    calculate_heikin_ashi,
    caculate_rsi,
    calculate_exponential_moving_average,
    calculate_weighted_moving_average,
    get_ema,
    get_stochastic,
    get_heikin_ashi,
    get_rsi,
    get_ohlcv, calculate_reverse_rsi, calculate_renko_series,
)


class TradingStatus(models.TextChoices):
    UP = "up", "UP"
    DOWN = "dn", "Down"


class StockData(models.Model):
    created_date = models.DateField(verbose_name="Created Date", auto_now_add=True)
    updated_date = models.DateField(verbose_name="Updated Date", auto_now=True)

    symbol = models.CharField(max_length=50, verbose_name="Symbol")
    company_name = models.CharField(max_length=200, verbose_name="Company Name", null=True, blank=True)
    smart_token = models.CharField(max_length=50, verbose_name="Smart Token", null=True, blank=True)
    smart_token_fetched = models.BooleanField(verbose_name="Smart Token Fetched", default=False)

    is_wk_fetched = models.BooleanField(verbose_name="Week Fetched", default=False)
    wk_open = models.FloatField(verbose_name="Open", null=True, blank=True)
    wk_high = models.FloatField(verbose_name="High", null=True, blank=True)
    wk_low = models.FloatField(verbose_name="Low", null=True, blank=True)
    wk_close = models.FloatField(verbose_name="Close", null=True, blank=True)
    wk_close_0 = models.FloatField(verbose_name="Close", null=True, blank=True)
    wk_close_1 = models.FloatField(verbose_name="Close", null=True, blank=True)
    wk_close_2 = models.FloatField(verbose_name="Close", null=True, blank=True)
    wk_close_3 = models.FloatField(verbose_name="Close", null=True, blank=True)
    wk_close_4 = models.FloatField(verbose_name="Close", null=True, blank=True)
    wk_close_5 = models.FloatField(verbose_name="Close", null=True, blank=True)
    wk_volume = models.FloatField(verbose_name="Volume", null=True, blank=True)
    wk_ema_5_0 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    wk_ema_14_0 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    wk_ema_20_0 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    wk_ema_50_0 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    wk_ema_200_0 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    wk_stoch_black_0 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    wk_stoch_red_0 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    wk_ha_open_0 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    wk_ha_high_0 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    wk_ha_low_0 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    wk_ha_close_0 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    wk_rsi_0 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    wk_ema_5_1 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    wk_ema_14_1 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    wk_ema_20_1 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    wk_ema_50_1 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    wk_ema_200_1 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    wk_stoch_black_1 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    wk_stoch_red_1 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    wk_ha_open_1 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    wk_ha_high_1 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    wk_ha_low_1 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    wk_ha_close_1 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    wk_rsi_1 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    wk_ema_5_2 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    wk_ema_14_2 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    wk_ema_20_2 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    wk_ema_50_2 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    wk_ema_200_2 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    wk_stoch_black_2 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    wk_stoch_red_2 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    wk_ha_open_2 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    wk_ha_high_2 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    wk_ha_low_2 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    wk_ha_close_2 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    wk_rsi_2 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    wk_ema_5_3 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    wk_ema_14_3 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    wk_ema_20_3 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    wk_ema_50_3 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    wk_ema_200_3 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    wk_stoch_black_3 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    wk_stoch_red_3 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    wk_ha_open_3 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    wk_ha_high_3 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    wk_ha_low_3 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    wk_ha_close_3 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    wk_rsi_3 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    wk_ema_5_4 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    wk_ema_14_4 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    wk_ema_20_4 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    wk_ema_50_4 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    wk_ema_200_4 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    wk_stoch_black_4 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    wk_stoch_red_4 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    wk_ha_open_4 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    wk_ha_high_4 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    wk_ha_low_4 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    wk_ha_close_4 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    wk_rsi_4 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    wk_ema_5_5 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    wk_ema_14_5 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    wk_ema_20_5 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    wk_ema_50_5 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    wk_ema_200_5 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    wk_stoch_black_5 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    wk_stoch_red_5 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    wk_ha_open_5 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    wk_ha_high_5 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    wk_ha_low_5 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    wk_ha_close_5 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    wk_rsi_5 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    wk_rev_rsi_60 = models.FloatField(verbose_name="Reverse RSI", null=True, blank=True)
    wk_rev_rsi_50 = models.FloatField(verbose_name="Reverse RSI", null=True, blank=True)
    wk_rev_rsi_40 = models.FloatField(verbose_name="Reverse RSI", null=True, blank=True)

    is_day_fetched = models.BooleanField(verbose_name="Day Fetched", default=False)
    day_open = models.FloatField(verbose_name="Open", null=True, blank=True)
    day_high = models.FloatField(verbose_name="High", null=True, blank=True)
    day_low = models.FloatField(verbose_name="Low", null=True, blank=True)
    day_close = models.FloatField(verbose_name="Close", null=True, blank=True)
    day_close_0 = models.FloatField(verbose_name="Close", null=True, blank=True)
    day_close_1 = models.FloatField(verbose_name="Close", null=True, blank=True)
    day_close_2 = models.FloatField(verbose_name="Close", null=True, blank=True)
    day_close_3 = models.FloatField(verbose_name="Close", null=True, blank=True)
    day_close_4 = models.FloatField(verbose_name="Close", null=True, blank=True)
    day_close_5 = models.FloatField(verbose_name="Close", null=True, blank=True)
    day_volume = models.FloatField(verbose_name="Volume", null=True, blank=True)
    day_ema_5_0 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    day_ema_14_0 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    day_ema_20_0 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    day_ema_50_0 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    day_ema_200_0 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    day_stoch_black_0 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    day_stoch_red_0 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    day_ha_open_0 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    day_ha_high_0 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    day_ha_low_0 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    day_ha_close_0 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    day_rsi_0 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    day_ema_5_1 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    day_ema_14_1 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    day_ema_20_1 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    day_ema_50_1 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    day_ema_200_1 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    day_stoch_black_1 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    day_stoch_red_1 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    day_ha_open_1 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    day_ha_high_1 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    day_ha_low_1 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    day_ha_close_1 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    day_rsi_1 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    day_ema_5_2 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    day_ema_14_2 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    day_ema_20_2 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    day_ema_50_2 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    day_ema_200_2 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    day_stoch_black_2 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    day_stoch_red_2 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    day_ha_open_2 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    day_ha_high_2 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    day_ha_low_2 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    day_ha_close_2 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    day_rsi_2 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    day_ema_5_3 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    day_ema_14_3 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    day_ema_20_3 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    day_ema_50_3 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    day_ema_200_3 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    day_stoch_black_3 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    day_stoch_red_3 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    day_ha_open_3 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    day_ha_high_3 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    day_ha_low_3 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    day_ha_close_3 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    day_rsi_3 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    day_ema_5_4 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    day_ema_14_4 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    day_ema_20_4 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    day_ema_50_4 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    day_ema_200_4 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    day_stoch_black_4 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    day_stoch_red_4 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    day_ha_open_4 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    day_ha_high_4 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    day_ha_low_4 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    day_ha_close_4 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    day_rsi_4 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    day_ema_5_5 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    day_ema_14_5 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    day_ema_20_5 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    day_ema_50_5 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    day_ema_200_5 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    day_stoch_black_5 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    day_stoch_red_5 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    day_ha_open_5 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    day_ha_high_5 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    day_ha_low_5 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    day_ha_close_5 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    day_rsi_5 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    day_rev_rsi_60 = models.FloatField(verbose_name="Reverse RSI", null=True, blank=True)
    day_rev_rsi_50 = models.FloatField(verbose_name="Reverse RSI", null=True, blank=True)
    day_rev_rsi_40 = models.FloatField(verbose_name="Reverse RSI", null=True, blank=True)

    is_hr_fetched = models.BooleanField(verbose_name="Hour Fetched", default=False)
    hr_open = models.FloatField(verbose_name="Open", null=True, blank=True)
    hr_high = models.FloatField(verbose_name="High", null=True, blank=True)
    hr_low = models.FloatField(verbose_name="Low", null=True, blank=True)
    hr_close = models.FloatField(verbose_name="Close", null=True, blank=True)
    hr_close_0 = models.FloatField(verbose_name="Close", null=True, blank=True)
    hr_close_1 = models.FloatField(verbose_name="Close", null=True, blank=True)
    hr_close_2 = models.FloatField(verbose_name="Close", null=True, blank=True)
    hr_close_3 = models.FloatField(verbose_name="Close", null=True, blank=True)
    hr_close_4 = models.FloatField(verbose_name="Close", null=True, blank=True)
    hr_close_5 = models.FloatField(verbose_name="Close", null=True, blank=True)
    hr_volume = models.FloatField(verbose_name="Volume", null=True, blank=True)
    hr_ema_5_0 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    hr_ema_14_0 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    hr_ema_20_0 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    hr_ema_50_0 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    hr_ema_200_0 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    hr_stoch_black_0 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    hr_stoch_red_0 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    hr_ha_open_0 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    hr_ha_high_0 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    hr_ha_low_0 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    hr_ha_close_0 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    hr_rsi_0 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    hr_ema_5_1 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    hr_ema_14_1 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    hr_ema_20_1 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    hr_ema_50_1 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    hr_ema_200_1 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    hr_stoch_black_1 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    hr_stoch_red_1 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    hr_ha_open_1 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    hr_ha_high_1 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    hr_ha_low_1 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    hr_ha_close_1 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    hr_rsi_1 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    hr_ema_5_2 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    hr_ema_14_2 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    hr_ema_20_2 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    hr_ema_50_2 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    hr_ema_200_2 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    hr_stoch_black_2 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    hr_stoch_red_2 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    hr_ha_open_2 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    hr_ha_high_2 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    hr_ha_low_2 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    hr_ha_close_2 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    hr_rsi_2 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    hr_ema_5_3 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    hr_ema_14_3 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    hr_ema_20_3 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    hr_ema_50_3 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    hr_ema_200_3 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    hr_stoch_black_3 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    hr_stoch_red_3 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    hr_ha_open_3 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    hr_ha_high_3 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    hr_ha_low_3 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    hr_ha_close_3 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    hr_rsi_3 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    hr_ema_5_4 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    hr_ema_14_4 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    hr_ema_20_4 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    hr_ema_50_4 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    hr_ema_200_4 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    hr_stoch_black_4 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    hr_stoch_red_4 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    hr_ha_open_4 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    hr_ha_high_4 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    hr_ha_low_4 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    hr_ha_close_4 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    hr_rsi_4 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    hr_ema_5_5 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    hr_ema_14_5 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    hr_ema_20_5 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    hr_ema_50_5 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    hr_ema_200_5 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    hr_stoch_black_5 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    hr_stoch_red_5 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    hr_ha_open_5 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    hr_ha_high_5 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    hr_ha_low_5 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    hr_ha_close_5 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    hr_rsi_5 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    hr_rev_rsi_60 = models.FloatField(verbose_name="Reverse RSI", null=True, blank=True)
    hr_rev_rsi_50 = models.FloatField(verbose_name="Reverse RSI", null=True, blank=True)
    hr_rev_rsi_40 = models.FloatField(verbose_name="Reverse RSI", null=True, blank=True)

    is_m15_fetched = models.BooleanField(verbose_name="15 Min Fetched", default=False)
    m15_open = models.FloatField(verbose_name="Open", null=True, blank=True)
    m15_high = models.FloatField(verbose_name="High", null=True, blank=True)
    m15_low = models.FloatField(verbose_name="Low", null=True, blank=True)
    m15_close = models.FloatField(verbose_name="Close", null=True, blank=True)
    m15_close_0 = models.FloatField(verbose_name="Close", null=True, blank=True)
    m15_close_1 = models.FloatField(verbose_name="Close", null=True, blank=True)
    m15_close_2 = models.FloatField(verbose_name="Close", null=True, blank=True)
    m15_close_3 = models.FloatField(verbose_name="Close", null=True, blank=True)
    m15_close_4 = models.FloatField(verbose_name="Close", null=True, blank=True)
    m15_close_5 = models.FloatField(verbose_name="Close", null=True, blank=True)
    m15_volume = models.FloatField(verbose_name="Volume", null=True, blank=True)
    m15_ema_5_0 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    m15_ema_14_0 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    m15_ema_20_0 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    m15_ema_50_0 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    m15_ema_200_0 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    m15_stoch_black_0 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    m15_stoch_red_0 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    m15_ha_open_0 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    m15_ha_high_0 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    m15_ha_low_0 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    m15_ha_close_0 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    m15_rsi_0 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    m15_ema_5_1 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    m15_ema_14_1 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    m15_ema_20_1 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    m15_ema_50_1 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    m15_ema_200_1 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    m15_stoch_black_1 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    m15_stoch_red_1 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    m15_ha_open_1 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    m15_ha_high_1 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    m15_ha_low_1 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    m15_ha_close_1 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    m15_rsi_1 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    m15_ema_5_2 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    m15_ema_14_2 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    m15_ema_20_2 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    m15_ema_50_2 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    m15_ema_200_2 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    m15_stoch_black_2 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    m15_stoch_red_2 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    m15_ha_open_2 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    m15_ha_high_2 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    m15_ha_low_2 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    m15_ha_close_2 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    m15_rsi_2 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    m15_ema_5_3 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    m15_ema_14_3 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    m15_ema_20_3 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    m15_ema_50_3 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    m15_ema_200_3 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    m15_stoch_black_3 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    m15_stoch_red_3 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    m15_ha_open_3 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    m15_ha_high_3 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    m15_ha_low_3 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    m15_ha_close_3 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    m15_rsi_3 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    m15_ema_5_4 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    m15_ema_14_4 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    m15_ema_20_4 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    m15_ema_50_4 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    m15_ema_200_4 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    m15_stoch_black_4 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    m15_stoch_red_4 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    m15_ha_open_4 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    m15_ha_high_4 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    m15_ha_low_4 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    m15_ha_close_4 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    m15_rsi_4 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    m15_ema_5_5 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    m15_ema_14_5 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    m15_ema_20_5 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    m15_ema_50_5 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    m15_ema_200_5 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    m15_stoch_black_5 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    m15_stoch_red_5 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    m15_ha_open_5 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    m15_ha_high_5 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    m15_ha_low_5 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    m15_ha_close_5 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    m15_rsi_5 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    m15_rev_rsi_60 = models.FloatField(verbose_name="Reverse RSI", null=True, blank=True)
    m15_rev_rsi_50 = models.FloatField(verbose_name="Reverse RSI", null=True, blank=True)
    m15_rev_rsi_40 = models.FloatField(verbose_name="Reverse RSI", null=True, blank=True)

    is_m5_fetched = models.BooleanField(verbose_name="5 Min Fetched", default=False)
    m5_open = models.FloatField(verbose_name="Open", null=True, blank=True)
    m5_high = models.FloatField(verbose_name="High", null=True, blank=True)
    m5_low = models.FloatField(verbose_name="Low", null=True, blank=True)
    m5_close = models.FloatField(verbose_name="Close", null=True, blank=True)
    m5_close_0 = models.FloatField(verbose_name="Close", null=True, blank=True)
    m5_close_1 = models.FloatField(verbose_name="Close", null=True, blank=True)
    m5_close_2 = models.FloatField(verbose_name="Close", null=True, blank=True)
    m5_close_3 = models.FloatField(verbose_name="Close", null=True, blank=True)
    m5_close_4 = models.FloatField(verbose_name="Close", null=True, blank=True)
    m5_close_5 = models.FloatField(verbose_name="Close", null=True, blank=True)
    m5_volume = models.FloatField(verbose_name="Volume", null=True, blank=True)
    m5_ema_5_0 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    m5_ema_14_0 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    m5_ema_20_0 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    m5_ema_50_0 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    m5_ema_200_0 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    m5_stoch_black_0 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    m5_stoch_red_0 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    m5_ha_open_0 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    m5_ha_high_0 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    m5_ha_low_0 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    m5_ha_close_0 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    m5_rsi_0 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    m5_ema_5_1 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    m5_ema_14_1 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    m5_ema_20_1 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    m5_ema_50_1 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    m5_ema_200_1 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    m5_stoch_black_1 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    m5_stoch_red_1 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    m5_ha_open_1 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    m5_ha_high_1 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    m5_ha_low_1 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    m5_ha_close_1 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    m5_rsi_1 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    m5_ema_5_2 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    m5_ema_14_2 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    m5_ema_20_2 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    m5_ema_50_2 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    m5_ema_200_2 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    m5_stoch_black_2 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    m5_stoch_red_2 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    m5_ha_open_2 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    m5_ha_high_2 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    m5_ha_low_2 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    m5_ha_close_2 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    m5_rsi_2 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    m5_ema_5_3 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    m5_ema_14_3 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    m5_ema_20_3 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    m5_ema_50_3 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    m5_ema_200_3 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    m5_stoch_black_3 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    m5_stoch_red_3 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    m5_ha_open_3 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    m5_ha_high_3 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    m5_ha_low_3 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    m5_ha_close_3 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    m5_rsi_3 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    m5_ema_5_4 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    m5_ema_14_4 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    m5_ema_20_4 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    m5_ema_50_4 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    m5_ema_200_4 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    m5_stoch_black_4 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    m5_stoch_red_4 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    m5_ha_open_4 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    m5_ha_high_4 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    m5_ha_low_4 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    m5_ha_close_4 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    m5_rsi_4 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    m5_ema_5_5 = models.FloatField(verbose_name="EMA 5", null=True, blank=True)
    m5_ema_14_5 = models.FloatField(verbose_name="EMA 14", null=True, blank=True)
    m5_ema_20_5 = models.FloatField(verbose_name="EMA 20", null=True, blank=True)
    m5_ema_50_5 = models.FloatField(verbose_name="EMA 50", null=True, blank=True)
    m5_ema_200_5 = models.FloatField(verbose_name="EMA 200", null=True, blank=True)
    m5_stoch_black_5 = models.FloatField(verbose_name="Stoch Black", null=True, blank=True)
    m5_stoch_red_5 = models.FloatField(verbose_name="Stoch Red", null=True, blank=True)
    m5_ha_open_5 = models.FloatField(verbose_name="HA Open", null=True, blank=True)
    m5_ha_high_5 = models.FloatField(verbose_name="HA High", null=True, blank=True)
    m5_ha_low_5 = models.FloatField(verbose_name="HA Low", null=True, blank=True)
    m5_ha_close_5 = models.FloatField(verbose_name="HA Close", null=True, blank=True)
    m5_rsi_5 = models.FloatField(verbose_name="RSI", null=True, blank=True)
    m5_rev_rsi_60 = models.FloatField(verbose_name="Reverse RSI", null=True, blank=True)
    m5_rev_rsi_50 = models.FloatField(verbose_name="Reverse RSI", null=True, blank=True)
    m5_rev_rsi_40 = models.FloatField(verbose_name="Reverse RSI", null=True, blank=True)

    trading_updated_at = models.DateTimeField(verbose_name="Trading Updated at", null=True, blank=True)
    is_trading = models.BooleanField(verbose_name="Is Trading", default=False)
    trading_status = models.CharField(max_length=2, choices=TradingStatus.choices, null=True, blank=True)

    objects = models.Manager()

    class Meta:
        ordering = ["symbol"]
        constraints = [models.UniqueConstraint(fields=["symbol"], name="%(app_label)s_%(class)s_unique_stock")]

    def __str__(self):
        """String representation of trend"""
        return self.symbol

    def get_smart_token(self):
        """Get smart token from api"""
        try:
            obj = SmartInstrument(instrument=self.symbol)
            result = obj.get_instrument()
            self.smart_token = str(result.get("token"))
        except:
            pass

        self.smart_token_fetched = True
        self.save()

    def get_smart_ohlc(self, interval, days):
        """Get Open, High, Low, Close from smart API"""
        from_date = datetime.now() - relativedelta(days=days)
        tag_data = get_param_config_tag(tag="SMART_HISTORY")
        smart = SmartTool(**tag_data)
        smart.get_object()
        history_data = smart.get_historical_data(
            exchange="NSE",
            symboltoken=self.smart_token,
            interval=interval,
            fromdate=from_date.strftime("%Y-%m-%d %H:%M"),
            todate=datetime.now().strftime("%Y-%m-%d %H:%M"),
        )

        df = pd.DataFrame(history_data)
        df[["date", "open", "high", "low", "close", "volume"]] = pd.DataFrame(df.data.tolist(), index=df.index)
        df["date"] = pd.to_datetime(df["date"])

        return df

    def reset_date_ohlc(self, df):
        """Convert the daily data OHLC to weekly"""
        logic = {
            "open": "first",
            "high": "max",
            "low": "min",
            "close": "last",
            "volume": "sum",
        }

        df["date"] = pd.to_datetime(df["date"])
        df.set_index("date", inplace=True)
        dfw = df.resample("W").apply(logic)
        dfw.index = dfw.index - pd.tseries.frequencies.to_offset("6D")
        dfw.reset_index(inplace=True)
        return dfw

    def get_fetch_params(self, data_type):
        params = {
            "wk": ("ONE_DAY", 900),
            "day": ("ONE_DAY", 400),
            "hr": ("ONE_HOUR", 60),
            "m15": ("FIFTEEN_MINUTE", 60),
            "m5": ("FIVE_MINUTE", 60),
        }
        return params.get(data_type)

    def generate_trend_value(self, data_type, df=None):
        """Generate trend value"""
        if not self.smart_token:
            return None

        try:
            interval, days = self.get_fetch_params(data_type)
            if df is None:
                df = self.get_smart_ohlc(interval=interval, days=days)
            if data_type == "wk":
                self.generate_trend_value("day", df=df)
                df = self.reset_date_ohlc(df=df)

            if data_type == "m5":
                self.trading_updated_at = df.iloc[-1]["date"]

            df_ohlcv = get_ohlcv(df=df, data_type=data_type)
            df_ha = calculate_heikin_ashi(df=df)
            df_ema = calculate_weighted_moving_average(df=df_ha)
            df_stoch = calculate_stochastic(df=df_ha)
            df_rsi = caculate_rsi(df=df_ha)
            df_reverse_rsi_60 = calculate_reverse_rsi(df=df_ha, rsi_given=60.0)
            df_reverse_rsi_50 = calculate_reverse_rsi(df=df_ha, rsi_given=50.0)
            df_reverse_rsi_40 = calculate_reverse_rsi(df=df_ha, rsi_given=40.0)
            # renko_series = calculate_renko_series(df)

            data_ema = get_ema(df_ema, data_type)
            data_stoch = get_stochastic(df_stoch, data_type)
            data_ha = get_heikin_ashi(df_ha, data_type)
            data_rsi = get_rsi(df_rsi, data_type)

            all_data = df_ohlcv | data_ema | data_stoch | data_ha | data_rsi
            for attr, value in all_data.items():
                setattr(self, attr, value)

            setattr(self, f"is_{data_type}_fetched", True)
            if df_reverse_rsi_60 and df_reverse_rsi_50 and df_reverse_rsi_40 :
                setattr(self,  f"{data_type}_rev_rsi_60", df_reverse_rsi_60)
                setattr(self,  f"{data_type}_rev_rsi_60", df_reverse_rsi_50)
                setattr(self,  f"{data_type}_rev_rsi_60", df_reverse_rsi_40)
            self.save()
            print(f"------------------{self.symbol}----{data_type}------------------")
        except ValueError as ve:
            print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
            print(ve)
            print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
        except AttributeError as ae:
            print(ae)


        return True
